//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPMRVPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class partymember
    {
        public partymember()
        {
            this.reservationitem_partymember = new HashSet<reservationitem_partymember>();
        }
    
        public long ID { get; set; }
        public string cellPhone { get; set; }
        public string petDescription { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
    
        public virtual person person { get; set; }
        public virtual ICollection<reservationitem_partymember> reservationitem_partymember { get; set; }
    }
}
