//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPMRVPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ipmevent
    {
        public ipmevent()
        {
            this.placemarkpolygons = new HashSet<placemarkpolygon>();
            this.sitetypes = new HashSet<sitetype>();
        }
    
        public long ID { get; set; }
        public long year { get; set; }
        public string local { get; set; }
        public string description { get; set; }
        public string mapFileUrl { get; set; }
    
        public virtual ICollection<placemarkpolygon> placemarkpolygons { get; set; }
        public virtual ICollection<sitetype> sitetypes { get; set; }
    }
}
