//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPMRVPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sitetype
    {
        public sitetype()
        {
            this.placemarkpolygons = new HashSet<placemarkpolygon>();
            this.siterates = new HashSet<siterate>();
        }
    
        public long ID { get; set; }
        public long idIPMEvent { get; set; }
        public string StyleUrl { get; set; }
        public string backgroundColor { get; set; }
        public long idSiteSize { get; set; }
        public long idPowerSupply { get; set; }
        public Nullable<bool> isUnserviced { get; set; }
        public Nullable<bool> isForHandicapped { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
    
        public virtual ipmevent ipmevent { get; set; }
        public virtual ICollection<placemarkpolygon> placemarkpolygons { get; set; }
        public virtual powersupply powersupply { get; set; }
        public virtual ICollection<siterate> siterates { get; set; }
        public virtual sitesize sitesize { get; set; }
    }
}
