//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPMRVPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coordinate
    {
        public long ID { get; set; }
        public long idIPMEvent { get; set; }
        public long idPlaceInMap { get; set; }
        public int seqCoordinate { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public System.DateTime createDate { get; set; }
        public System.DateTime lastUpdate { get; set; }
    
        public virtual ipmevent ipmevent { get; set; }
        public virtual placeinmap placeinmap { get; set; }
    }
}
