//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPMRVPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_view
    {
        public long id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string fullName { get; set; }
        public string mainPhone { get; set; }
        public string email { get; set; }
        public string cellPhone { get; set; }
        public string homePhone { get; set; }
        public string faxNumber { get; set; }
        public string comments { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string postalCode { get; set; }
        public string countryCode { get; set; }
        public string countryName { get; set; }
        public string provinceCode { get; set; }
        public string provinceName { get; set; }
        public Nullable<bool> isEmailReceipt { get; set; }
        public Nullable<bool> isPartyMember { get; set; }
    }
}
