//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPMRVPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ipmevent
    {
        public ipmevent()
        {
            this.placemarkpolygons = new HashSet<placemarkpolygon>();
            this.siterates = new HashSet<siterate>();
            this.styleurls = new HashSet<styleurl>();
        }
    
        public int idIPMEvent { get; set; }
        public Nullable<int> year { get; set; }
        public string local { get; set; }
        public string description { get; set; }
        public string mapFileUrl { get; set; }
    
        public virtual ICollection<placemarkpolygon> placemarkpolygons { get; set; }
        public virtual ICollection<siterate> siterates { get; set; }
        public virtual ICollection<styleurl> styleurls { get; set; }
    }
}
