//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPMRVPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public payment()
        {
            this.reservationgroups = new HashSet<reservationgroup>();
        }
    
        public int idPayment { get; set; }
        public int idPaymentMode { get; set; }
        public decimal amount { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
    
        public virtual paymentmode paymentmode { get; set; }
        public virtual ICollection<reservationgroup> reservationgroups { get; set; }
    }
}
