//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPMRVPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class placemarkpolygon
    {
        public placemarkpolygon()
        {
            this.coordinates = new HashSet<coordinate>();
        }
    
        public string idPlacemarkPolygon { get; set; }
        public string name { get; set; }
        public string idStyleUrl { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
    
        public virtual ICollection<coordinate> coordinates { get; set; }
        public virtual rvsite rvsite { get; set; }
        public virtual styleurl styleurl { get; set; }
    }
}
