//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPMRVPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class placeinmap
    {
        public placeinmap()
        {
            this.checkinouts = new HashSet<checkinout>();
            this.coordinates = new HashSet<coordinate>();
            this.outofserviceitems = new HashSet<outofserviceitem>();
            this.reservationitems = new HashSet<reservationitem>();
            this.selecteditems = new HashSet<selecteditem>();
        }
    
        public long ID { get; set; }
        public long idIPMEvent { get; set; }
        public string tag { get; set; }
        public string site { get; set; }
        public long idSiteType { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
        public Nullable<bool> isRVSite { get; set; }
    
        public virtual ICollection<checkinout> checkinouts { get; set; }
        public virtual ICollection<coordinate> coordinates { get; set; }
        public virtual ipmevent ipmevent { get; set; }
        public virtual ICollection<outofserviceitem> outofserviceitems { get; set; }
        public virtual sitetype sitetype { get; set; }
        public virtual ICollection<reservationitem> reservationitems { get; set; }
        public virtual ICollection<selecteditem> selecteditems { get; set; }
    }
}
