//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPMRVPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class province_view
    {
        public string provinceCode { get; set; }
        public string provinceName { get; set; }
        public string countryCode { get; set; }
        public string countryName { get; set; }
    }
}
