//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPMRVPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservationeach
    {
        public reservationeach()
        {
            this.checkinouts = new HashSet<checkinout>();
        }
    
        public int idReservationGroup { get; set; }
        public int idReservationEach { get; set; }
        public string idRVSite { get; set; }
        public int idParty { get; set; }
        public System.DateTime arrivalDate { get; set; }
        public System.DateTime departureDate { get; set; }
        public Nullable<decimal> totalAmount { get; set; }
        public bool isCancelled { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
    
        public virtual ICollection<checkinout> checkinouts { get; set; }
        public virtual party party { get; set; }
        public virtual rvsite rvsite { get; set; }
        public virtual reservationgroup reservationgroup { get; set; }
    }
}
