//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPMRVPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public staff()
        {
            this.reservationitems = new HashSet<reservationitem>();
            this.selecteditems = new HashSet<selecteditem>();
            this.sessions = new HashSet<session>();
        }
    
        public long ID { get; set; }
        public string role { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
    
        public virtual person person { get; set; }
        public virtual ICollection<reservationitem> reservationitems { get; set; }
        public virtual ICollection<selecteditem> selecteditems { get; set; }
        public virtual ICollection<session> sessions { get; set; }
    }
}
