//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPMRVPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempperson
    {
        public string number { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string provinceCode { get; set; }
        public string countryCode { get; set; }
        public string postalCode { get; set; }
        public string mainPhone { get; set; }
        public string alternatePhone { get; set; }
        public string collegeEmail { get; set; }
        public string temppersonalEmail { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
    }
}
