//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPMRVPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temprvsite
    {
        public string idPlacemarkPolygon { get; set; }
        public string name { get; set; }
        public string idStyleUrl { get; set; }
        public Nullable<decimal> c1x { get; set; }
        public Nullable<decimal> c1y { get; set; }
        public Nullable<decimal> c2x { get; set; }
        public Nullable<decimal> c2y { get; set; }
        public Nullable<decimal> c3x { get; set; }
        public Nullable<decimal> c3y { get; set; }
        public Nullable<decimal> c4x { get; set; }
        public Nullable<decimal> c4y { get; set; }
    }
}
