//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPMRVPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class total_per_customer_view
    {
        public long id { get; set; }
        public string fullName { get; set; }
        public string mainPhone { get; set; }
        public Nullable<decimal> balance { get; set; }
    }
}
