//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPMRVPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class total_per_payment_view
    {
        public long idPayment { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string reasonForPayment { get; set; }
        public Nullable<long> idCustomer { get; set; }
        public Nullable<long> idStaff { get; set; }
        public Nullable<decimal> paymentAmount { get; set; }
        public Nullable<decimal> reservationitem_total { get; set; }
        public decimal balance { get; set; }
    }
}
